### ISSUE TITLE
Need Support of Multiple subtitles

### ISSUE THREAD

**Issue by shafqat-muneer** [mhergon/MPMoviePlayerController-Subtitles#10]
Hi,
How to handle multiple SRT files on MPMoviePlayerController? I also want this support in this library.
Thanks,
Shafqat

**Comment by mhergon** [comment]
Hi @shafqat-muneer 

What do you mean with multiple SRT files support? multiple SRT files playing at the same time?

**Comment by shafqat-muneer** [comment]
Hi @mhergon 
One SRT file will be played once but user had option to switch between language; Have a look at this http://stackoverflow.com/questions/32902133/how-to-handle-multiple-srt-files-on-mpmovieplayercontroller

**Comment by mhergon** [comment]
I'm preparing the next version, I will try to add support for multi language.
Greetings!

**Comment by shafqat-muneer** [comment]
Alright Thanks.

**Comment by shafqat-muneer** [comment]
Hi,

I have done work over multiple subtitles; Now library can parse N SRT files; If you wish, i can send you pull request.

Thanks,
Shafqat

**Comment by mhergon** [comment]
Send me a pull request

Thanks!
