### ISSUE TITLE
Parser is failed to parse some files

### ISSUE THREAD

**Issue by shafqat-muneer** [mhergon/MPMoviePlayerController-Subtitles#11]
Hi @mhergon ,

I am facing some issue during parsing two files.
https://dl.dropboxusercontent.com/u/32254461/Subtitles/English.srt [Successfully Parsing]
https://dl.dropboxusercontent.com/u/32254461/Subtitles/Espanish.srt [Failed to Parse]

Both files structure is same. You can view it by tapping on links.

Code is breaking on these lines:
                NSString *textString;
                [scanner scanUpToString:@"\r\n\r\n" intoString:&textString];
                textString = [textString stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceCharacterSet]];

"textString" is returning whole file data at once in case of some files. These are just sample files; Its also breaking for many English and Espanish files.

Please look into the issue; If i am doing something wrong then please let me know.

Thanks,
Shafqat

**Comment by mhergon** [comment]
Please, remove "WEBVTT FILE" and the other blank lines at the top and try again

**Comment by shafqat-muneer** [comment]
Still not working after removing "WEBVTT FILE" and the other blank lines at the top;
Actually with "WEBVTT FILE" entry, its working for some files as well.

**Comment by kudeiro** [comment]
i also had problems with an srt in Spanish, i solved it changing NSUTF8StringEncoding to NSASCIIStringEncoding

**Comment by shafqat-muneer** [comment]
I have also tried it by changing NSUTF8StringEncoding to NSASCIIStringEncoding. Its still not working; Can you please try it by using above Espanish file? Thanks

**Comment by shafqat-muneer** [comment]
Hi,

I have fixed this issue at my side.

Investigated Issue:
Hidden Characters Sequence in English SRT Files: \r\n\r\n
Hidden Characters Sequence in Spanish SRT Files: \n\n\n

So, we need to handled both of them. It seems to be working perfectly after syncing both of these flavours.

If you wish, i can generate pull request for this changes. For this, i need some permissions over github; Otherwise, you can add following line in MPMoviePlayerController+Subtitles.m after Line#56.

subtitleString = [subtitleString stringByReplacingOccurrencesOfString:@"\n\n\n" withString:@"\r\n\r\n"];

Thanks,
Shafqat

**Comment by mhergon** [comment]
Send me a pull request

Thanks!

**Comment by shafqat-muneer** [comment]
After executing git push origin SRT-File-IssueFix command, i am getting following error:

remote: Permission to mhergon/MPMoviePlayerController-Subtitles.git denied to shafqat-muneer.

fatal: unable to access 'https://github.com/mhergon/MPMoviePlayerController-Subtitles.git/': The requested URL returned error: 403

**Comment by mhergon** [comment]
@shafqat-muneer 
Please, check merged files

**Comment by shafqat-muneer** [comment]
Yes; Merged perfectly. Thanks.
I have also create pull request https://github.com/mhergon/MPMoviePlayerController-Subtitles/pull/13 for Multi language SRT support. Please have a look.

**Comment by mhergon** [comment]
Please, check merged
Thanks!

**Comment by shafqat-muneer** [comment]
Working perfectly.
Thanks,
Shafqat
