### ISSUE TITLE
Terminating app due to uncaught exception 'NSInternalInconsistencyException'

### ISSUE THREAD

**Issue by tuanbs** [mhergon/MPMoviePlayerController-Subtitles#14]
Hello, I got this issue when reading video and its sub:
"Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSDictionaryOfVariableBindings failed because either one of the values is nil, or there's something wrong with the way the macro is being invoked.  Cannot assign value nil for key "weakSubtitleLabel". Keys:(
    weakSubtitleLabel
)'"
I created this subtitle by following:
[self.item.srtSubtitle writeToFile:srtSubPath atomically:YES encoding:NSUTF8StringEncoding error:&error];
The video and its sub can be downloaded here: https://www.dropbox.com/sh/zgmxujxerydhz9q/AAAlQp7sAMW2_ISJwZ9NO47Xa?dl=0#
I've been trying to create the sub with different encoding like: NSUTF8StringEncoding, NSISOLatin1StringEncoding but no luck.
Please help me. Thank you.

**Comment by mhergon** [comment]
@tuanbs I tried and works correctly. Please, download last version from Github an try again.
