### ISSUE TITLE
subtitleLabel blinking in 2 positions

### ISSUE THREAD

**Issue by zikoops** [mhergon/MPMoviePlayerController-Subtitles#15]
Hi, first i really thanks you for the library, it help me alot.

I have using your library to reading subtitles in my video player, it's works fine, subtitle is showing when i watching video but it blinking in 2 positions.
May you want to watching clip for more detail.

https://www.dropbox.com/s/op2z83nyagfu2t0/Video%20Nov%2013%2C%2014%2002%2050.mov?dl=0

I have running your example code and it has the same issue.

**Comment by mhergon** [comment]
HI @zikoops 

Could you send me the code to take a look?

Thanks!

**Comment by zikoops** [comment]
Sorry i can't send your my project, but i have tried run your example code downloaded from github and it have same issue, you can check your example.
I'm running on xcode 7 and ios 8.1, ios 9
Thanks for reply :)

**Comment by zikoops** [comment]
Here is your example running on xcode 7.1

https://www.dropbox.com/s/wezzsgowwnc1g5m/Video%20Nov%2013%2C%2022%2010%2039.mov?dl=0

**Comment by zikoops** [comment]
:( 2 days.... can you help me? @mhergon

**Comment by mhergon** [comment]
Hi @zikoops,

I'm pretty busy, but after review my code, seems to be ok.
Otherwise, If I rebuild all framework en Swift, would be a problem for you?

Thanks!

**Comment by zikoops** [comment]
Hi @mhergon 
If you can rebuild all framework to Swift, that is helpful for me because i'm using swift.

Thanks!
P/s: Sorry for my terrible english.

**Comment by mhergon** [comment]
Hi @zikoops 

I'm rewriting the framework as Swift Extension. Please, wait a few days and I will finish and test new v2.0
Thanks for the patient.

PS: my English is worse ;)

**Comment by mhergon** [comment]
Hi @zikoops 

I finished a new version of the new framework. Can you test with your project?
New framework is an extension of MPMoviePlayerController and is fairly simple to use. Dropbox link contains extension and example.

Please, send any feedback or issue with this:
https://www.dropbox.com/s/1lyq5ku4hrc25wh/MPMoviePlayerController-Subtitles%20v%202.0.zip?dl=0

Thanks!

**Comment by zikoops** [comment]
Hi @mhergon 
Wow!!!! you are amazing, i have tried your new version of the framework with my project and it's works, no blink subtitle on 2 positions anymore (y).
But it had a new issue, it can't reading my subtitle file (*.srt), if srt file is ISO encode it'll throw an exception, so i fix it with:

func open(file filePath: NSURL) {
        let contents = try! String(contentsOfURL: filePath, encoding: NSISOLatin1StringEncoding)
        show(subtitles: contents)
}

it's work, but subtitles still not showing....
I have tried copy all of contents in my srt file into your example srt file so it work well, i don't know why but i think it's had problems with Encoding of the file.

My srt file: https://www.dropbox.com/s/f3000fiu5d84q0a/subtitle-iso-encoding.srt?dl=0

Thanks!

**Comment by mhergon** [comment]
HI again @zikoops 

First of all, thanks for testing!
After your comments, I improved the library. Parsing is much more efficient and support file encoding.

Example
```swift
moviePlayer.moviePlayer.addSubtitles().open(file: subtitleURL)
```
or        
```
swiftmoviePlayer.moviePlayer.addSubtitles().open(file: subtitleURL, encoding: NSUTF8StringEncoding)
```

Please, try again and if everything is ok, I will upload new version and release.

New code:
https://www.dropbox.com/s/rlyicqc3a2wi4iv/MPMoviePlayerController-Subtitles%20v2.0%282%29.zip?dl=0

Thanks again!

**Comment by zikoops** [comment]
Hallo @mhergon 

The framework works perfectly, I will continue to test for many different cases, if there are any problems I will inform you.

Thank you very much for your enthusiastic support!
Thanks you again, again, again and againnnnnnnnnnnnnn. :+1:

**Comment by mhergon** [comment]
Hi @zikoops 

New version is available on Cocoapods

Thanks!
