### ISSUE TITLE
Trying to use this with AVPLayerViewController

### ISSUE THREAD

**Issue by Enmud** [mhergon/MPMoviePlayerController-Subtitles#16]
Hi I am trying to port this code to work with AVPlayerViewController with below  minimal changes. 

 // Video file
        let videoFile = NSBundle.mainBundle().pathForResource("trailer_720p", ofType: "mov")
        
        // Subtitle file
        let subtitleFile = NSBundle.mainBundle().pathForResource("trailer_720p", ofType: "srt")
        let subtitleURL = NSURL(fileURLWithPath: subtitleFile!)
        // Using AVPLAyerViewController
        let moviePlayerViewAV = AVPlayerViewController()
        moviePlayerViewAV.player = AVPlayer(URL: NSURL(fileURLWithPath: videoFile!))
        moviePlayerViewAV.addSubtitles().open(file: subtitleURL)
        moviePlayerViewAV.addSubtitles().open(file: subtitleURL, encoding: NSUTF8StringEncoding)
        // Change text properties
        moviePlayerViewAV.subtitleLabel?.textColor = UIColor.redColor()
        // Play
        moviePlayerViewAV.player!.play()
        
And some changes in extension file.
Below code is throwing exception "Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Unable to parse constraint format: 
Unable to interpret '|' character, because the related view doesn't have a superview 
H:|-(20)-[l]-(20)-| "

subtitleContainer?.translatesAutoresizingMaskIntoConstraints =  false
            subtitleLabel?.translatesAutoresizingMaskIntoConstraints = false
            var constraints = NSLayoutConstraint.constraintsWithVisualFormat("H:|-(20)-[l]-(20)-|", options: NSLayoutFormatOptions(rawValue: 0), metrics: nil, views: ["l" : subtitleLabel!])
            subtitleContainer?.addConstraints(constraints)
            constraints = NSLayoutConstraint.constraintsWithVisualFormat("V:[l]-(30)-|", options: NSLayoutFormatOptions(rawValue: 0), metrics: nil, views: ["l" : subtitleLabel!])
            
            subtitleContainer?.addConstraints(constraints)
            subtitleLabelHeightConstraint = NSLayoutConstraint(item: subtitleLabel!, attribute: .Height, relatedBy: .Equal, toItem: nil, attribute: NSLayoutAttribute.NotAnAttribute, multiplier: 1.0, constant: 30.0)

Any help is appreciated.

**Comment by mhergon** [comment]
Hi @Enmud 

I have adapted the library for the new AVPlayerViewController APIs. You can check it in this repo.
https://github.com/mhergon/AVPlayerViewController-Subtitles

Regards!

**Comment by Enmud** [comment]
@mhergon  Thank you mhergon. You saved my day.
