### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by nguyenhaidang** [mhergon/MPMoviePlayerController-Subtitles#17]
When video haven't display if you rotate screen your app will crash. Because this code

- (void)updateLabelConstraints {
    
    // Default
    NSString *horizontal = @"H:|-(15)-[weakSubtitleLabel]-(15)-|";
    NSString *vertical = @"V:[weakSubtitleLabel]-(15)-|";
    
    UIView __weak *weakSubtitleLabel = self.subtitleLabel;
// Crash because weakSubtitleLable = nil
      NSDictionary *views = NSDictionaryOfVariableBindings(weakSubtitleLabel);
        NSArray *constraints = [NSLayoutConstraint constraintsWithVisualFormat:horizontal
                                                                       options:0
                                                                       metrics:nil
                                                                         views:views];
        [self.subtitleLabel.superview addConstraints:constraints];
        constraints = [NSLayoutConstraint constraintsWithVisualFormat:vertical
                                                              options:0
                                                              metrics:nil
                                                                views:views];
        [self.subtitleLabel.superview addConstraints:constraints];
        
        
        CGRect bounds = [self.subtitleLabel.text boundingRectWithSize:CGSizeMake(CGRectGetWidth(self.subtitleLabel.bounds), CGFLOAT_MAX)
                                                              options:NSStringDrawingUsesLineFragmentOrigin
                                                           attributes:@{NSFontAttributeName : self.subtitleLabel.font}
                                                              context:nil];
        self.heightConstraint.constant = bounds.size.height + 10.0;
        
        [self.subtitleLabel.superview layoutIfNeeded];
}

---- So I change a little in this code

- (void)updateLabelConstraints {
    
    // Default
    NSString *horizontal = @"H:|-(15)-[weakSubtitleLabel]-(15)-|";
    NSString *vertical = @"V:[weakSubtitleLabel]-(15)-|";
    
    UIView __weak *weakSubtitleLabel = self.subtitleLabel;
    __if (weakSubtitleLabel)__ {
        NSDictionary *views = NSDictionaryOfVariableBindings(weakSubtitleLabel);
        NSArray *constraints = [NSLayoutConstraint constraintsWithVisualFormat:horizontal
                                                                       options:0
                                                                       metrics:nil
                                                                         views:views];
        [self.subtitleLabel.superview addConstraints:constraints];
        constraints = [NSLayoutConstraint constraintsWithVisualFormat:vertical
                                                              options:0
                                                              metrics:nil
                                                                views:views];
        [self.subtitleLabel.superview addConstraints:constraints];
        
        
        CGRect bounds = [self.subtitleLabel.text boundingRectWithSize:CGSizeMake(CGRectGetWidth(self.subtitleLabel.bounds), CGFLOAT_MAX)
                                                              options:NSStringDrawingUsesLineFragmentOrigin
                                                           attributes:@{NSFontAttributeName : self.subtitleLabel.font}
                                                              context:nil];
        self.heightConstraint.constant = bounds.size.height + 10.0;
        
        [self.subtitleLabel.superview layoutIfNeeded];
    }
}

**Comment by mhergon** [comment]
Hi @nguyenhaidang 

Hi,

This Objective-C version of the library is deprecated. Please, use the last Swift version that correct this issue and have others improvements.
https://github.com/mhergon/MPMoviePlayerController-Subtitles.git

You can mixing Objective-C and Swift files flawlessly. Follow this steps to make it work:
https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html

Thanks!

**Comment by nguyenhaidang** [comment]
Thank you :)
