### ISSUE TITLE
Support for objective c and to use .plist

### ISSUE THREAD

**Issue by vanditmehta** [mhergon/MPMoviePlayerController-Subtitles#18]
Hello mhergon,

First of all great job you have done with this library 

Can you please provide update in Objective c and suggest me to a way for use .plist file instead of .srt file

**Comment by mhergon** [comment]
Hi @vanditmehta 

You can use Swift version on your Objective-C projects. Please, refer to this issue for instructions (last message).
https://github.com/mhergon/MPMoviePlayerController-Subtitles/issues/17

About .plist, what do you want to do exactly?

**Comment by vanditmehta** [comment]
We want to create dynamic control where user can touch and add some text from some time stamp to some another time stamp

**Comment by mhergon** [comment]
Hi @vanditmehta 

The library supports strings and .srt files. If you create string manually, you will be able to read the string and show with the library.
