### ISSUE TITLE
asynchronous between sound and video after while

### ISSUE THREAD

**Issue by hassan379** [mhergon/MPMoviePlayerController-Subtitles#19]
thx for this great lib
but i think there is an issue, asynchronous between sound and video after while,what i mean that there is no match between sound and the scene after a while and this issue appears only if  there is subtitle.
thx in advance

**Comment by mhergon** [comment]
Hi hassan379,

I will try to reproduce the issue, but I need an example video and subtitle to test it.

Thanks!

**Comment by hassan379** [comment]
here is the subtitle :
http://techsoft2016.byethost12.com/subtitles/ipman.srt
and here is the video link:
http://www.spruto.tv/get_file/2/980e72a475984041ec6a13c3593adbd6/162000/162404/162404.mp4
thx in advance

**Comment by mhergon** [comment]
Hi,

I tried with local and remote mp4 and works correctly. Please, review your code.
