### ISSUE TITLE
Can it play online video?

### ISSUE THREAD

**Issue by yuchin067** [mhergon/MPMoviePlayerController-Subtitles#22]
I try use online video, the link is http://jplayer.org/video/m4v/Big_Buck_Bunny_Trailer.m4v
My code as follows,
`let moviePlayerView = MPMoviePlayerViewController(contentURL: NSURL(string: "http://jplayer.org/video/m4v/Big_Buck_Bunny_Trailer.m4v"))`

It doesn't work. Can it support online video?

**Comment by mhergon** [comment]
Hi,

The video is played? Or subtitles doesn't appear?

**Comment by yuchin067** [comment]
Hi,
I'm sorry I did not speak clearly.
The video does not play.

**Comment by mhergon** [comment]
`MPMoviePlayerController-Subtitles` is an extension of `MPMoviePlayerController`.
Thus, all videos that works with `MPMoviePlayerController` should be work with `MPMoviePlayerController-Subtitles`

**Comment by yuchin067** [comment]
I think so, but the video can play with MPMoviePlayerController. It doesn't work with MPMoviePlayerController-Subtitles.

**Comment by mhergon** [comment]
Hi,

Are you trying directly on example app of the library? If yes, my console shows this error:
`App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure. Temporary exceptions can be configured via your app's Info.plist file.
`
Do you have the same error?

**Comment by yuchin067** [comment]
The message of App Transport Security has blocked a cleartext is not shown in my console.
According to your suggestion, I set the Info.plist file.
It can work find now. Thank you very much.
