### ISSUE TITLE
Does not parse the tags in the WEBVTT files

### ISSUE THREAD

**Issue by Nikita989** [mhergon/MPMoviePlayerController-Subtitles#23]
Below is my WEBVTT file:
![screen shot 2017-07-24 at 6 34 28 pm](https://user-images.githubusercontent.com/22230651/28524615-df057c56-709e-11e7-8a96-8a94ffc13cfb.png)
 The  "c" tag used here is displayed as a string. Does it not implicitly parse the tags?

**Comment by mhergon** [comment]
WEBVTT not supported
