### ISSUE TITLE
Subtitle Not Display in fullscreen mode

### ISSUE THREAD

**Issue by mineshpurohit** [mhergon/MPMoviePlayerController-Subtitles#9]
Subtitle was not displaying when MPMoviePlayerController In full screen mode.

**Comment by mhergon** [comment]
Hi,

Can you give me more info or code related?
If you have an example project with this issue I will try to fix it.

Thanks!

**Comment by mineshpurohit** [comment]
Yes I had implement as per mention below:

    // Video file
    NSString *filePathStr = [[NSBundle mainBundle] pathForResource:@"example" ofType:@"mp4"];
    NSURL *fileURL = [NSURL fileURLWithPath:filePathStr];
    
    // Subtitles file
    NSString *subtitlesPathStr = [[NSBundle mainBundle] pathForResource:@"example" ofType:@"srt"];
    
    // Create MoviePlayer
    MPMoviePlayerController *player = [[MPMoviePlayerController alloc] initWithContentURL:fileURL];
    [player.view setFrame:CGRectMake(0, 0, 320, 480)];
    [player openSRTFileAtPath:subtitlesPathStr
                               completion:^(BOOL finished) {
                                   // Activate subtitles
                                   [player showSubtitles];
                               } failure:^(NSError *error) {
                                   NSLog(@"Error: %@", error.description);
                               }];
    [self.view addSubview:player.view];
  
    [player play];
    
    // And On click of custom button action set full screen mode.
    [player setFullscreen:YES animated:YES];

**Comment by mhergon** [comment]
Hi,

Why you do not use MPMoviePlayerViewController instead of MPMoviePlayerController? 
Is there any reason for this?

**Comment by mineshpurohit** [comment]
Because of at first time I need to show video at particular rectangle of the screen And when user click on full screen button at that time only i need to play video in full screen mode.

**Comment by mhergon** [comment]
Hi,

A new version is available. 

Thanks!

**Comment by mineshpurohit** [comment]
Hi,
Thanks, It's really save my time.
Working like a charm.

**Comment by mhergon** [comment]
@mineshpurohit Please, update it again to v1.0.4. I found a tiny bug.

Thanks!
